"""Generate the ONNX model-contract fixtures: a conforming kcp-13 value model, its manifests, and the
Python-side inference outputs the JVM parity test compares against (engine #78).

Unlike the other synthetic fixtures here, this model satisfies the *serving contract* shared with
dicechess-training: one FLOAT input named ``input`` shaped ``[batch, 13]``, one FLOAT output named
``output`` shaped ``[batch, 1]``, and a bounded (sigmoid) output that is a probability rather than an
unbounded regression score. The older fixtures name their output ``variable``, which is exactly the
mismatch ``OnnxModelContract`` exists to reject.

The graph is linear plus a sigmoid, so every expected value can be recomputed by hand:

    p = sigmoid(sum(WEIGHTS[i] * features[i]) + BIAS)

Run with a Python environment that has onnx + onnxruntime + numpy (the dicechess-training venv is one):

    python3 generate_model_contract_fixtures.py
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import numpy as np
import onnx
import onnxruntime as ort
from onnx import TensorProto, helper

SCHEMA = "kcp-13"
FEATURE_COUNT = 13
INPUT_NAME = "input"
OUTPUT_NAME = "output"
MODEL_FILE = "synthetic_kcp13_value_test_model.onnx"
RENAMED_MODEL_FILE = "synthetic_kcp13_renamed_tensors_test_model.onnx"
RENAMED_INPUT_NAME = "features"
RENAMED_OUTPUT_NAME = "win_probability"
PARITY_FILE = "synthetic_kcp13_value_parity.json"
ENGINE_COMPATIBILITY = ">=0.12.0 <1.0.0"

# One weight per kcp-13 column, in KcpFeatures.columnNames order. Signs are the plausible ones (a king
# capture chance for us is good, one against us is bad) so a reader can sanity-check the fixture, but the
# magnitudes are arbitrary: this is a wiring and parity fixture, never a trained model.
#
# king_safety_diff (column 8) carries a deliberately small weight. Its range is an order of magnitude wider
# than every other column's (probes reach -2000), and at 0.02 two of the nine probes drove the sigmoid to
# exactly 0.0 — rows on which no Python/JVM disagreement could ever show up, because both sides saturate.
# At 0.0002 every probe lands inside (0.09, 0.77) and the seven unsaturated expected values are unchanged.
WEIGHTS = [0.5, 0.3, 0.3, 0.2, 0.15, 0.1, 0.005, 0.02, 0.0002, 2.0, -2.0, 0.5, -0.5]
BIAS = -0.1

# Probe positions with the 13-column vectors the engine extracts for them, copied from the train/serve
# golden corpus of dicechess-training (tests/fixtures/kcp13/golden-engine-0.12.0.json, generated by
# tools/kcp13-golden against engine 0.12.0). The JVM parity test re-extracts these vectors with
# KcpFeatures and fails if they ever drift, so the copy cannot rot silently.
PROBES = [
    {
        "id": 'start-w',
        "fen": 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq -',
        "side": 'w',
        "features": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 78.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    },
    {
        "id": 'start-b',
        "fen": 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR b KQkq -',
        "side": 'b',
        "features": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 78.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    },
    {
        "id": 'kings-only-w',
        "fen": '4k3/8/8/8/8/8/8/4K3 w - -',
        "side": 'w',
        "features": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    },
    {
        "id": 'knight-up-w',
        "fen": 'r1bqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq -',
        "side": 'w',
        "features": [0.0, 1.0, 0.0, 0.0, 0.0, 3.0, 75.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    },
    {
        "id": 'knight-up-w-twin',
        "fen": 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/R1BQKBNR b KQkq -',
        "side": 'b',
        "features": [0.0, 1.0, 0.0, 0.0, 0.0, 3.0, 75.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    },
    {
        "id": 'rook-king-danger-w',
        "fen": '4k3/8/8/8/8/8/4r3/4K3 w - -',
        "side": 'w',
        "features": [0.0, 0.0, 0.0, -1.0, 0.0, -5.0, 5.0, -13.0, -2000.0, 0.0, 0.4212963, 0.0, 0.0],
    },
    {
        "id": 'rook-queen-attack-w',
        "fen": 'k7/8/8/4q3/8/8/8/K3R3 w - -',
        "side": 'w',
        "features": [0.0, 0.0, 0.0, 1.0, -1.0, -4.0, 14.0, -17.0, -2000.0, 0.018518519, 0.4212963, 0.4212963, 0.0],
    },
    {
        "id": 'passed-pawn-w',
        "fen": 'k7/4P3/8/8/8/8/8/4K3 w - -',
        "side": 'w',
        "features": [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 6.0, 0.0, 0.2777778, 0.0, 0.0, 0.0],
    },
    {
        "id": 'sample-mid-b',
        "fen": 'r1bk4/ppp3pp/8/1BP5/2P5/8/R2K2QP/4R3 b - -',
        "side": 'b',
        "features": [2.0, 0.0, 0.0, -1.0, -1.0, -12.0, 38.0, -36.0, 0.0, 0.0, 0.14814815, 0.074074075, 0.0],
    },
]


def make_model(
    graph_name: str = "synthetic-kcp13-value",
    input_name: str = INPUT_NAME,
    output_name: str = OUTPUT_NAME,
) -> onnx.ModelProto:
    """The same weights under configurable tensor names.

    The renamed variant exists to prove that a conforming graph is fed by the name its manifest declares rather than
    by the literal ``input``: identical weights mean the two models must score identically, so a difference can only
    come from the plumbing.
    """
    weights = helper.make_tensor("weights", TensorProto.FLOAT, [FEATURE_COUNT, 1], WEIGHTS)
    bias = helper.make_tensor("bias", TensorProto.FLOAT, [1], [BIAS])
    graph = helper.make_graph(
        [
            helper.make_node("MatMul", [input_name, "weights"], ["weighted"]),
            helper.make_node("Add", ["weighted", "bias"], ["logit"]),
            helper.make_node("Sigmoid", ["logit"], [output_name]),
        ],
        graph_name,
        [helper.make_tensor_value_info(input_name, TensorProto.FLOAT, ["batch", FEATURE_COUNT])],
        [helper.make_tensor_value_info(output_name, TensorProto.FLOAT, ["batch", 1])],
        [weights, bias],
    )
    model = helper.make_model(graph, opset_imports=[helper.make_opsetid("", 13)], ir_version=8)
    onnx.checker.check_model(model, full_check=True)
    return model


def manifest(
    digest: str,
    model_id: str,
    version: str,
    role: str | None,
    input_name: str = INPUT_NAME,
    output_name: str = OUTPUT_NAME,
) -> dict:
    common = {
        "manifestVersion": version,
        "modelId": model_id,
        "modelSha256": digest,
        "featureSchema": SCHEMA,
        "featureCount": FEATURE_COUNT,
        "engineCompatibility": ENGINE_COMPATIBILITY,
        "calibration": {"temperature": 1.0},
        "provenance": {
            "generator": "jvm/src/test/resources/generate_model_contract_fixtures.py",
            "purpose": "engine #78 model-contract test fixture",
            "trained": "false",
        },
    }
    if version == "1.0.0":
        # The version the evaluation service and the kcp-13 serving contract emit: no role, no
        # perspective, no tensor names, and an evaluation profile the engine records but never uses.
        return {**common, "evaluationProfile": "standard-kcp"}
    return {
        **common,
        "modelRole": role,
        "inputName": input_name,
        "outputName": output_name,
        "perspective": "side-to-move",
    }


def write_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path.name}")


def main() -> None:
    base = Path(__file__).parent
    model_path = base / MODEL_FILE
    onnx.save(make_model(), model_path)
    print(f"wrote {model_path.name}")
    digest = hashlib.sha256(model_path.read_bytes()).hexdigest()

    write_json(
        base / "synthetic_kcp13_value_manifest.json",
        manifest(digest, "synthetic-kcp13-value", "1.1.0", "position-value"),
    )
    write_json(
        base / "synthetic_kcp13_value_legacy_manifest.json",
        manifest(digest, "synthetic-kcp13-value-legacy", "1.0.0", None),
    )
    write_json(
        base / "synthetic_kcp13_collapse_manifest.json",
        manifest(digest, "synthetic-kcp13-collapse", "1.1.0", "chance-collapse"),
    )

    renamed_path = base / RENAMED_MODEL_FILE
    onnx.save(
        make_model("synthetic-kcp13-renamed", RENAMED_INPUT_NAME, RENAMED_OUTPUT_NAME),
        renamed_path,
    )
    print(f"wrote {renamed_path.name}")
    write_json(
        base / "synthetic_kcp13_renamed_tensors_manifest.json",
        manifest(
            hashlib.sha256(renamed_path.read_bytes()).hexdigest(),
            "synthetic-kcp13-renamed",
            "1.1.0",
            "position-value",
            RENAMED_INPUT_NAME,
            RENAMED_OUTPUT_NAME,
        ),
    )

    rows = np.asarray([probe["features"] for probe in PROBES], dtype=np.float32)
    session = ort.InferenceSession(str(model_path), providers=["CPUExecutionProvider"])
    (outputs,) = session.run([OUTPUT_NAME], {INPUT_NAME: rows})
    assert outputs.shape == (len(PROBES), 1), outputs.shape
    write_json(
        base / PARITY_FILE,
        {
            "schema": SCHEMA,
            "perspective": "side-to-move",
            "model": MODEL_FILE,
            "modelSha256": digest,
            "generator": "jvm/src/test/resources/generate_model_contract_fixtures.py",
            "runtime": f"onnxruntime {ort.__version__} (Python, CPUExecutionProvider)",
            "featureSource": "dicechess-training tests/fixtures/kcp13/golden-engine-0.12.0.json",
            "columns": [
                "p_diff",
                "n_diff",
                "b_diff",
                "r_diff",
                "q_diff",
                "material_diff",
                "total_material",
                "mobility_diff",
                "king_safety_diff",
                "king_capture_attack",
                "king_capture_danger",
                "queen_capture_attack",
                "queen_capture_danger",
            ],
            "probes": [
                {**probe, "output": float(outputs[index][0])}
                for index, probe in enumerate(PROBES)
            ],
        },
    )


if __name__ == "__main__":
    main()
