package dicechess.engine.search

import java.io.File
import java.net.URLEncoder
import java.nio.file.Files

/** Generates the visual Markdown catalog of KingCaptureProbability test cases from Scala fixtures.
  *
  * This generator bridges test fixtures with published documentation: it ensures the Astro documentation site reflects
  * the exact test positions and expected king capture probabilities vetted by automated tests without manual copy-paste
  * drift.
  */
object KingCaptureDocGenerator:

  def main(args: Array[String]): Unit =
    println("Starting documentation generation for KingCaptureProbability Test Cases...")

    val cases = KingCaptureFixtures.cases

    val sb = new StringBuilder()
    sb.append("---\n")
    sb.append("title: King Capture Probability Test Cases\n")
    sb.append("description: Visual catalog of expert-vetted test cases for king capture probability analysis.\n")
    sb.append("sidebar:\n")
    sb.append("  order: 2\n")
    sb.append("---\n\n")
    sb.append("<!-- @generated by KingCaptureDocGenerator.scala - do not edit directly -->\n\n")

    sb.append(
      "This page catalogs all our active test cases for king capture probability, allowing developers to visually inspect and verify scenarios.\n\n"
    )

    for (tc, index) <- cases.zipWithIndex do
      val caseNum = index + 1

      // Generate Lichess FEN image URL — strip the 7th dice field (not part of standard FEN)
      val standardFen = tc.fen.split(" ").take(6).mkString(" ")
      val cleanFen    = standardFen.replace(' ', '_')
      val encodedFen  = URLEncoder.encode(cleanFen, "UTF-8")
      val boardColor  = if tc.fen.split(" ").lift(1).contains("w") then "white" else "black"
      val imgUrl      =
        s"https://lichess1.org/export/fen.gif?fen=$encodedFen&color=$boardColor&theme=brown&piece=cburnett"

      val probStr =
        String.format(java.util.Locale.US, "%.2f%%", java.lang.Double.valueOf(tc.expectedKingProbability * 100))
      val probabilityFraction = s"${tc.winningRolls}/216"
      val defendedColor       = if tc.defenderColor.isWhite then "White" else "Black"

      sb.append(s"## $caseNum. ${tc.name}\n\n")
      sb.append(
        s"""<div style="display: flex; flex-direction: row; gap: 24px; align-items: start; margin-bottom: 30px; flex-wrap: wrap;">
  <div style="flex: 1; min-width: 300px;">
    <p style="margin-top: 0; margin-bottom: 16px;">${tc.description}</p>
    <ul style="list-style-type: disc; padding-left: 20px; margin-bottom: 0;">
      <li style="margin-bottom: 8px;"><strong>Expected Probability:</strong> <code>$probStr ($probabilityFraction)</code></li>
      <li style="margin-bottom: 8px;"><strong>Defended Color:</strong> <code>$defendedColor</code></li>
      <li style="margin-bottom: 8px;"><strong>Combinatorial rationale:</strong> ${tc.rationale}</li>
      <li style="margin-bottom: 0;"><strong>FEN:</strong> <code>${tc.fen}</code></li>
    </ul>
  </div>
  <div style="flex: 0 0 280px; width: 280px; min-width: 280px; margin: 0 auto;">
    <img src="$imgUrl" alt="${tc.name}" style="width: 100%; border-radius: 8px; box-shadow: 0 4px 10px rgba(0,0,0,0.15); border: 1px solid rgba(0,0,0,0.08);" />
  </div>
</div>

---

"""
      )

    // Write to Astro docs content folder
    val outputFile = new File("docs/src/content/docs/architecture/search/02-king-capture-probability-test-cases.md")
    outputFile.getParentFile.mkdirs()
    Files.writeString(outputFile.toPath, sb.toString())
    println(s"Successfully generated visual test cases catalog at: ${outputFile.getAbsolutePath}")
